project:
  type: website
  output-dir: docs

website:
  title: "SPEI – Cogotí y Ramadas"
  navbar:
    left:
      # AHORA LAS RUTAS INCLUYEN EL NOMBRE DE LA CARPETA
      - href: pagina-quarto/index.qmd
        text: Inicio
      - href: pagina-quarto/spei.qmd
        text: Análisis SPEI
      - href: pagina-quarto/precipitacion.qmd
        text: Precipitación

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css