project:
  type: website
  output-dir: docs

website:
  title: "Sequía en Limarí Precordillerano"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: README.md
        text: Sobre el proyecto
      - href: spei.qmd
        text: Código de análisis de Precipitación

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    lang: es      